[tool.poetry]
name = "radiopi"
version = "0.1.0"
description = "All we hear is RadioPi..."
authors = ["Dave Hall <dave@etianen.com>"]
license = "UNLICENCED"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
gpiozero = "^2.0"
"rpi.gpio" = { version = "^0.7.1", markers = "sys_platform == 'linux'" }

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
ruff = "^0.1.11"

[tool.poetry.scripts]
radiopi = "radiopi:main"

[tool.mypy]
allow_redefinition = true
explicit_package_bases = true
namespace_packages = true
show_column_numbers = true
show_error_codes = true
strict = true
platform = "linux"

[[tool.mypy.overrides]]
module = ["gpiozero.*"]
ignore_missing_imports = true

[tool.ruff]
exclude = [".venv"]
line-length = 120
select = ["E", "F", "W", "I"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
