name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - run: pipx install poetry
    - run: poetry check
    - run: poetry check --lock
    - run: poetry install
