name: Build

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # Install toolchain.
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: "poetry"
    # Run pre-install checks.
    - run: poetry check
    - run: poetry check --lock
    # Activate venv.
    - run: |
        VIRTUAL_ENV=$(poetry env info --path)
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
    # Install dependencies.
    - name: Install dependencies
      run: poetry install
    # Run checks.
    - name: Check (ruff)
      run: ruff check
    - name: Check (ruff format)
      run: ruff format --check
    - name: Check (mypy)
      run: mypy
    # Run tests.
    - name: Test
      run: coverage run -m pytest
    # Report coverage.
    - name: Report coverage
      run: coverage report
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
