name: Build

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Install toolchain.
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: "poetry"
    # Run pre-install checks.
    - run: poetry check
    - run: poetry check --lock
    # Activate venv.
    - run: |
        VIRTUAL_ENV=$(poetry env info --path)
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
    # Install dependencies.
    - run: poetry install
    # Run checks.
    - run: ruff check
    - run: ruff format --check
    - run: mypy
    # Run tests.
    - run: pytest
